import { InputListProps } from "@/types/form.type";
import * as Yup from "yup";

export const FormInputList: InputListProps[] = [
  {
    name: "name",
    label: "Name",
    type: "input",
    validator: Yup.string().required("Name is required"),
    value: "",
    placeholder: "Input name here",
    isRequired: true,
  },
  {
    className: "mt-7",
    name: "description",
    label: "Description",
    type: "textarea",
    validator: Yup.string().required("Description is required"),
    value: "",
    placeholder: "Input description here",
    isRequired: true,
  },
  {
    className: "mt-7",
    name: "thumbnail",
    label: "Thumbnail",
    type: "image",
    validator: Yup.string().required("Thumbnail is required"),
    value: "",
    isRequired: true,
  },
  {
    className: "mt-7",
    name: "price",
    label: "Price",
    type: "currency",
    validator: Yup.number().typeError('Input should be a number').required("Price is required"),
    value: 0,
    isRequired: true,
  },
  {
    className: "mt-7",
    name: "quantity",
    label: "Quantity",
    type: "number",
    validator: Yup.number().typeError('Input should be a number').required("Quantity is required"),
    value: 1,
    placeholder: "Input quantity here",
    isRequired: true,
  },
  {
    className: "mt-7",
    name: "discount",
    label: "Discount",
    type: "number",
    validator: Yup.number().typeError('Input should be a number').optional(),
    value: 0,
    placeholder: "Input discount here",
    isRequired: false,
  },
];