import { ProductProps } from "./typeProps";
const DATA_PRODUCTS: ProductProps[] = [
    {
      id: 1,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
      name: "Spotify",
      price: 2500,
      date: "Wed 3:00pm",
      status: "paid",
      account: "visa",
      rating: 1234,
      createdAt: "06/2026",
    },
    {
      id: 2,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
      name: "Amazon",
      price: 5000,
      date: "Wed 1:00pm",
      status: "paid",
      account: "master-card",
      rating: 1234,
      createdAt: "06/2026",
    },
    {
      id: 3,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
      name: "Pinterest",
      price: 3400,
      date: "Mon 7:40pm",
      status: "pending",
      account: "master-card",
      rating: 1234,
      createdAt: "06/2026",
    },
    {
      id: 4,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
      name: "Google",
      price: 1000,
      date: "Wed 5:00pm",
      status: "paid",
      account: "visa",
      rating: 1234,
      createdAt: "06/2026",
    },
    {
      id: 5,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
      name: "Netflix",
      price: 14000,
      date: "Wed 3:30am",
      status: "cancelled",
      account: "visa",
      rating: 1234,
      createdAt: "06/2026",
    },
    {
      id: 6,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-apple.svg",
      name: "Apple",
      price: 12000,
      date: "Fri 11:00am",
      status: "paid",
      account: "master-card",
      rating: 1345,
      createdAt: "07/2026",
    },
    {
      id: 7,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
      name: "Facebook",
      price: 2700,
      date: "Thu 9:00pm",
      status: "pending",
      account: "visa",
      rating: 982,
      createdAt: "05/2026",
    },
    {
      id: 8,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-twitter.svg",
      name: "Twitter",
      price: 3000,
      date: "Sat 2:30pm",
      status: "cancelled",
      account: "master-card",
      rating: 1250,
      createdAt: "08/2026",
    },
    {
      id: 9,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-instagram.svg",
      name: "Instagram",
      price: 4000,
      date: "Mon 10:00am",
      status: "paid",
      account: "visa",
      rating: 1543,
      createdAt: "03/2026",
    },
    {
      id: 10,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-linkedin.svg",
      name: "LinkedIn",
      price: 2200,
      date: "Sun 7:30pm",
      status: "pending",
      account: "visa",
      rating: 875,
      createdAt: "04/2026",
    },
    {
      id: 11,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-slack.svg",
      name: "Slack",
      price: 1500,
      date: "Tue 1:00pm",
      status: "paid",
      account: "master-card",
      rating: 1000,
      createdAt: "02/2026",
    },
    {
      id: 12,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
      name: "Dribbble",
      price: 2600,
      date: "Wed 4:00pm",
      status: "paid",
      account: "visa",
      rating: 1350,
      createdAt: "06/2026",
    },
    {
      id: 13,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-youtube.svg",
      name: "YouTube",
      price: 5600,
      date: "Thu 5:00pm",
      status: "cancelled",
      account: "master-card",
      rating: 1980,
      createdAt: "07/2026",
    },
    {
      id: 14,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
      name: "Figma",
      price: 3700,
      date: "Fri 3:00pm",
      status: "pending",
      account: "visa",
      rating: 1450,
      createdAt: "05/2026",
    },
    {
      id: 15,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-github.svg",
      name: "GitHub",
      price: 2800,
      date: "Sat 8:00am",
      status: "paid",
      account: "master-card",
      rating: 1100,
      createdAt: "09/2026",
    },
    {
      id: 16,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-microsoft.svg",
      name: "Microsoft",
      price: 4300,
      date: "Sun 12:00pm",
      status: "paid",
      account: "visa",
      rating: 1420,
      createdAt: "10/2026",
    },
    {
      id: 17,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
      name: "Tesla",
      price: 9200,
      date: "Tue 11:30am",
      status: "pending",
      account: "master-card",
      rating: 1780,
      createdAt: "12/2026",
    },
    {
      id: 18,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
      name: "Airbnb",
      price: 3600,
      date: "Wed 2:00pm",
      status: "paid",
      account: "visa",
      rating: 1400,
      createdAt: "11/2026",
    },
    {
      id: 19,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-uber.svg",
      name: "Uber",
      price: 2900,
      date: "Thu 6:00pm",
      status: "cancelled",
      account: "master-card",
      rating: 1340,
      createdAt: "01/2027",
    },
    {
      id: 20,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-zoom.svg",
      name: "Zoom",
      price: 1900,
      date: "Fri 8:30pm",
      status: "pending",
      account: "visa",
      rating: 900,
      createdAt: "03/2027",
    },
    {
      id: 21,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
      name: "Spotify",
      price: 2500,
      date: "Sat 10:00am",
      status: "paid",
      account: "master-card",
      rating: 1234,
      createdAt: "04/2027",
    },
    {
      id: 22,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
      name: "Amazon",
      price: 5000,
      date: "Sun 2:00pm",
      status: "paid",
      account: "visa",
      rating: 1234,
      createdAt: "06/2027",
    },
    {
      id: 23,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
      name: "Pinterest",
      price: 3400,
      date: "Mon 4:00pm",
      status: "pending",
      account: "master-card",
      rating: 1234,
      createdAt: "07/2027",
    },
    {
      id: 24,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
      name: "Google",
      price: 1000,
      date: "Tue 9:00am",
      status: "paid",
      account: "visa",
      rating: 1234,
      createdAt: "08/2027",
    },
    {
      id: 25,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
      name: "Netflix",
      price: 14000,
      date: "Wed 11:30am",
      status: "cancelled",
      account: "master-card",
      rating: 1234,
      createdAt: "09/2027",
    },
    {
      id: 26,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
      name: "Airbnb",
      price: 7500,
      date: "Thu 1:00pm",
      status: "paid",
      account: "visa",
      rating: 1450,
      createdAt: "10/2027",
    },
    {
      id: 27,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
      name: "Facebook",
      price: 2900,
      date: "Fri 7:00pm",
      status: "pending",
      account: "master-card",
      rating: 980,
      createdAt: "11/2027",
    },
    {
      id: 28,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
      name: "Tesla",
      price: 9200,
      date: "Sat 3:30pm",
      status: "paid",
      account: "visa",
      rating: 1780,
      createdAt: "12/2027",
    },
    {
      id: 29,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
      name: "Dribbble",
      price: 2600,
      date: "Sun 9:30am",
      status: "paid",
      account: "master-card",
      rating: 1350,
      createdAt: "01/2028",
    },
    {
      id: 30,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
      name: "Figma",
      price: 3700,
      date: "Mon 8:30am",
      status: "pending",
      account: "visa",
      rating: 1450,
      createdAt: "02/2028",
    },
    {
      id: 31,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
      name: "Airbnb",
      price: 6200,
      date: "Tue 10:45am",
      status: "paid",
      account: "visa",
      rating: 1500,
      createdAt: "03/2028",
    },
    {
      id: 32,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
      name: "Facebook",
      price: 4100,
      date: "Wed 11:00am",
      status: "cancelled",
      account: "master-card",
      rating: 1300,
      createdAt: "04/2028",
    },
    {
      id: 33,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
      name: "Google",
      price: 7500,
      date: "Thu 2:30pm",
      status: "pending",
      account: "visa",
      rating: 1600,
      createdAt: "05/2028",
    },
    {
      id: 34,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
      name: "Amazon",
      price: 8200,
      date: "Fri 9:00am",
      status: "paid",
      account: "master-card",
      rating: 1250,
      createdAt: "06/2028",
    },
    {
      id: 35,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
      name: "Netflix",
      price: 14000,
      date: "Sat 1:45pm",
      status: "cancelled",
      account: "visa",
      rating: 1800,
      createdAt: "07/2028",
    },
    {
      id: 36,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
      name: "Spotify",
      price: 3000,
      date: "Sun 7:30pm",
      status: "pending",
      account: "master-card",
      rating: 1400,
      createdAt: "08/2028",
    },
    {
      id: 37,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
      name: "Dribbble",
      price: 2600,
      date: "Mon 9:00am",
      status: "paid",
      account: "visa",
      rating: 1350,
      createdAt: "09/2028",
    },
    {
      id: 38,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
      name: "Pinterest",
      price: 3400,
      date: "Tue 5:15pm",
      status: "paid",
      account: "master-card",
      rating: 1450,
      createdAt: "10/2028",
    },
    {
      id: 39,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
      name: "Figma",
      price: 3700,
      date: "Wed 10:00am",
      status: "pending",
      account: "visa",
      rating: 1500,
      createdAt: "11/2028",
    },
    {
      id: 40,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
      name: "Tesla",
      price: 9200,
      date: "Thu 3:30pm",
      status: "cancelled",
      account: "master-card",
      rating: 1700,
      createdAt: "12/2028",
    },
    {
      id: 41,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
      name: "Airbnb",
      price: 7400,
      date: "Fri 6:00pm",
      status: "paid",
      account: "visa",
      rating: 1550,
      createdAt: "01/2029",
    },
    {
      id: 42,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
      name: "Facebook",
      price: 2900,
      date: "Sat 8:45am",
      status: "pending",
      account: "master-card",
      rating: 1200,
      createdAt: "02/2029",
    },
    {
      id: 43,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
      name: "Google",
      price: 5200,
      date: "Sun 7:30pm",
      status: "paid",
      account: "visa",
      rating: 1550,
      createdAt: "03/2029",
    },
    {
      id: 44,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
      name: "Amazon",
      price: 7800,
      date: "Mon 10:00am",
      status: "cancelled",
      account: "master-card",
      rating: 1350,
      createdAt: "04/2029",
    },
    {
      id: 45,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
      name: "Netflix",
      price: 9000,
      date: "Tue 1:45pm",
      status: "paid",
      account: "visa",
      rating: 1600,
      createdAt: "05/2029",
    },
    {
      id: 46,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
      name: "Spotify",
      price: 4500,
      date: "Wed 9:30am",
      status: "pending",
      account: "master-card",
      rating: 1400,
      createdAt: "06/2029",
    },
    {
      id: 47,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
      name: "Dribbble",
      price: 3000,
      date: "Thu 11:00am",
      status: "paid",
      account: "visa",
      rating: 1300,
      createdAt: "07/2029",
    },
    {
      id: 48,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
      name: "Pinterest",
      price: 5000,
      date: "Fri 2:30pm",
      status: "cancelled",
      account: "master-card",
      rating: 1500,
      createdAt: "08/2029",
    },
    {
      id: 49,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
      name: "Figma",
      price: 6400,
      date: "Sat 10:00am",
      status: "paid",
      account: "visa",
      rating: 1450,
      createdAt: "09/2029",
    },
    {
      id: 50,
      description: "This is a description",
      image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
      name: "Tesla",
      price: 10200,
      date: "Sun 12:30pm",
      status: "pending",
      account: "master-card",
      rating: 1700,
      createdAt: "10/2029",
    },
  ];
  

  export { DATA_PRODUCTS };