import { ProductProps, PostProps, CategoryProps } from "./typeProps";
// const DATA_PRODUCTS: ProductProps[] = [
//     {
//       id: 1,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
//       name: "Spotify",
//       price: 2500,
//       date: "Wed 3:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1234,
//       createdAt: "06/2026",
//     },
//     {
//       id: 2,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
//       name: "Amazon",
//       price: 5000,
//       date: "Wed 1:00pm",
//       status: "paid",
//       account: "master-card",
//       rating: 1234,
//       createdAt: "06/2026",
//     },
//     {
//       id: 3,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
//       name: "Pinterest",
//       price: 3400,
//       date: "Mon 7:40pm",
//       status: "pending",
//       account: "master-card",
//       rating: 1234,
//       createdAt: "06/2026",
//     },
//     {
//       id: 4,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
//       name: "Google",
//       price: 1000,
//       date: "Wed 5:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1234,
//       createdAt: "06/2026",
//     },
//     {
//       id: 5,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
//       name: "Netflix",
//       price: 14000,
//       date: "Wed 3:30am",
//       status: "cancelled",
//       account: "visa",
//       rating: 1234,
//       createdAt: "06/2026",
//     },
//     {
//       id: 6,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-apple.svg",
//       name: "Apple",
//       price: 12000,
//       date: "Fri 11:00am",
//       status: "paid",
//       account: "master-card",
//       rating: 1345,
//       createdAt: "07/2026",
//     },
//     {
//       id: 7,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
//       name: "Facebook",
//       price: 2700,
//       date: "Thu 9:00pm",
//       status: "pending",
//       account: "visa",
//       rating: 982,
//       createdAt: "05/2026",
//     },
//     {
//       id: 8,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-twitter.svg",
//       name: "Twitter",
//       price: 3000,
//       date: "Sat 2:30pm",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1250,
//       createdAt: "08/2026",
//     },
//     {
//       id: 9,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-instagram.svg",
//       name: "Instagram",
//       price: 4000,
//       date: "Mon 10:00am",
//       status: "paid",
//       account: "visa",
//       rating: 1543,
//       createdAt: "03/2026",
//     },
//     {
//       id: 10,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-linkedin.svg",
//       name: "LinkedIn",
//       price: 2200,
//       date: "Sun 7:30pm",
//       status: "pending",
//       account: "visa",
//       rating: 875,
//       createdAt: "04/2026",
//     },
//     {
//       id: 11,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-slack.svg",
//       name: "Slack",
//       price: 1500,
//       date: "Tue 1:00pm",
//       status: "paid",
//       account: "master-card",
//       rating: 1000,
//       createdAt: "02/2026",
//     },
//     {
//       id: 12,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
//       name: "Dribbble",
//       price: 2600,
//       date: "Wed 4:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1350,
//       createdAt: "06/2026",
//     },
//     {
//       id: 13,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-youtube.svg",
//       name: "YouTube",
//       price: 5600,
//       date: "Thu 5:00pm",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1980,
//       createdAt: "07/2026",
//     },
//     {
//       id: 14,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
//       name: "Figma",
//       price: 3700,
//       date: "Fri 3:00pm",
//       status: "pending",
//       account: "visa",
//       rating: 1450,
//       createdAt: "05/2026",
//     },
//     {
//       id: 15,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-github.svg",
//       name: "GitHub",
//       price: 2800,
//       date: "Sat 8:00am",
//       status: "paid",
//       account: "master-card",
//       rating: 1100,
//       createdAt: "09/2026",
//     },
//     {
//       id: 16,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-microsoft.svg",
//       name: "Microsoft",
//       price: 4300,
//       date: "Sun 12:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1420,
//       createdAt: "10/2026",
//     },
//     {
//       id: 17,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
//       name: "Tesla",
//       price: 9200,
//       date: "Tue 11:30am",
//       status: "pending",
//       account: "master-card",
//       rating: 1780,
//       createdAt: "12/2026",
//     },
//     {
//       id: 18,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
//       name: "Airbnb",
//       price: 3600,
//       date: "Wed 2:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1400,
//       createdAt: "11/2026",
//     },
//     {
//       id: 19,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-uber.svg",
//       name: "Uber",
//       price: 2900,
//       date: "Thu 6:00pm",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1340,
//       createdAt: "01/2027",
//     },
//     {
//       id: 20,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-zoom.svg",
//       name: "Zoom",
//       price: 1900,
//       date: "Fri 8:30pm",
//       status: "pending",
//       account: "visa",
//       rating: 900,
//       createdAt: "03/2027",
//     },
//     {
//       id: 21,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
//       name: "Spotify",
//       price: 2500,
//       date: "Sat 10:00am",
//       status: "paid",
//       account: "master-card",
//       rating: 1234,
//       createdAt: "04/2027",
//     },
//     {
//       id: 22,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
//       name: "Amazon",
//       price: 5000,
//       date: "Sun 2:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1234,
//       createdAt: "06/2027",
//     },
//     {
//       id: 23,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
//       name: "Pinterest",
//       price: 3400,
//       date: "Mon 4:00pm",
//       status: "pending",
//       account: "master-card",
//       rating: 1234,
//       createdAt: "07/2027",
//     },
//     {
//       id: 24,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
//       name: "Google",
//       price: 1000,
//       date: "Tue 9:00am",
//       status: "paid",
//       account: "visa",
//       rating: 1234,
//       createdAt: "08/2027",
//     },
//     {
//       id: 25,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
//       name: "Netflix",
//       price: 14000,
//       date: "Wed 11:30am",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1234,
//       createdAt: "09/2027",
//     },
//     {
//       id: 26,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
//       name: "Airbnb",
//       price: 7500,
//       date: "Thu 1:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1450,
//       createdAt: "10/2027",
//     },
//     {
//       id: 27,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
//       name: "Facebook",
//       price: 2900,
//       date: "Fri 7:00pm",
//       status: "pending",
//       account: "master-card",
//       rating: 980,
//       createdAt: "11/2027",
//     },
//     {
//       id: 28,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
//       name: "Tesla",
//       price: 9200,
//       date: "Sat 3:30pm",
//       status: "paid",
//       account: "visa",
//       rating: 1780,
//       createdAt: "12/2027",
//     },
//     {
//       id: 29,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
//       name: "Dribbble",
//       price: 2600,
//       date: "Sun 9:30am",
//       status: "paid",
//       account: "master-card",
//       rating: 1350,
//       createdAt: "01/2028",
//     },
//     {
//       id: 30,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
//       name: "Figma",
//       price: 3700,
//       date: "Mon 8:30am",
//       status: "pending",
//       account: "visa",
//       rating: 1450,
//       createdAt: "02/2028",
//     },
//     {
//       id: 31,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
//       name: "Airbnb",
//       price: 6200,
//       date: "Tue 10:45am",
//       status: "paid",
//       account: "visa",
//       rating: 1500,
//       createdAt: "03/2028",
//     },
//     {
//       id: 32,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
//       name: "Facebook",
//       price: 4100,
//       date: "Wed 11:00am",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1300,
//       createdAt: "04/2028",
//     },
//     {
//       id: 33,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
//       name: "Google",
//       price: 7500,
//       date: "Thu 2:30pm",
//       status: "pending",
//       account: "visa",
//       rating: 1600,
//       createdAt: "05/2028",
//     },
//     {
//       id: 34,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
//       name: "Amazon",
//       price: 8200,
//       date: "Fri 9:00am",
//       status: "paid",
//       account: "master-card",
//       rating: 1250,
//       createdAt: "06/2028",
//     },
//     {
//       id: 35,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
//       name: "Netflix",
//       price: 14000,
//       date: "Sat 1:45pm",
//       status: "cancelled",
//       account: "visa",
//       rating: 1800,
//       createdAt: "07/2028",
//     },
//     {
//       id: 36,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
//       name: "Spotify",
//       price: 3000,
//       date: "Sun 7:30pm",
//       status: "pending",
//       account: "master-card",
//       rating: 1400,
//       createdAt: "08/2028",
//     },
//     {
//       id: 37,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
//       name: "Dribbble",
//       price: 2600,
//       date: "Mon 9:00am",
//       status: "paid",
//       account: "visa",
//       rating: 1350,
//       createdAt: "09/2028",
//     },
//     {
//       id: 38,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
//       name: "Pinterest",
//       price: 3400,
//       date: "Tue 5:15pm",
//       status: "paid",
//       account: "master-card",
//       rating: 1450,
//       createdAt: "10/2028",
//     },
//     {
//       id: 39,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
//       name: "Figma",
//       price: 3700,
//       date: "Wed 10:00am",
//       status: "pending",
//       account: "visa",
//       rating: 1500,
//       createdAt: "11/2028",
//     },
//     {
//       id: 40,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
//       name: "Tesla",
//       price: 9200,
//       date: "Thu 3:30pm",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1700,
//       createdAt: "12/2028",
//     },
//     {
//       id: 41,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-airbnb.svg",
//       name: "Airbnb",
//       price: 7400,
//       date: "Fri 6:00pm",
//       status: "paid",
//       account: "visa",
//       rating: 1550,
//       createdAt: "01/2029",
//     },
//     {
//       id: 42,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-facebook.svg",
//       name: "Facebook",
//       price: 2900,
//       date: "Sat 8:45am",
//       status: "pending",
//       account: "master-card",
//       rating: 1200,
//       createdAt: "02/2029",
//     },
//     {
//       id: 43,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
//       name: "Google",
//       price: 5200,
//       date: "Sun 7:30pm",
//       status: "paid",
//       account: "visa",
//       rating: 1550,
//       createdAt: "03/2029",
//     },
//     {
//       id: 44,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
//       name: "Amazon",
//       price: 7800,
//       date: "Mon 10:00am",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1350,
//       createdAt: "04/2029",
//     },
//     {
//       id: 45,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
//       name: "Netflix",
//       price: 9000,
//       date: "Tue 1:45pm",
//       status: "paid",
//       account: "visa",
//       rating: 1600,
//       createdAt: "05/2029",
//     },
//     {
//       id: 46,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
//       name: "Spotify",
//       price: 4500,
//       date: "Wed 9:30am",
//       status: "pending",
//       account: "master-card",
//       rating: 1400,
//       createdAt: "06/2029",
//     },
//     {
//       id: 47,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-dribbble.svg",
//       name: "Dribbble",
//       price: 3000,
//       date: "Thu 11:00am",
//       status: "paid",
//       account: "visa",
//       rating: 1300,
//       createdAt: "07/2029",
//     },
//     {
//       id: 48,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
//       name: "Pinterest",
//       price: 5000,
//       date: "Fri 2:30pm",
//       status: "cancelled",
//       account: "master-card",
//       rating: 1500,
//       createdAt: "08/2029",
//     },
//     {
//       id: 49,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-figma.svg",
//       name: "Figma",
//       price: 6400,
//       date: "Sat 10:00am",
//       status: "paid",
//       account: "visa",
//       rating: 1450,
//       createdAt: "09/2029",
//     },
//     {
//       id: 50,
//       description: "This is a description",
//       image: "https://docs.material-tailwind.com/img/logos/logo-tesla.svg",
//       name: "Tesla",
//       price: 10200,
//       date: "Sun 12:30pm",
//       status: "pending",
//       account: "master-card",
//       rating: 1700,
//       createdAt: "10/2029",
//     },
//   ];
  

//   const DATA_CATEGORIES: CategoryProps[] = [
//     {
//       id: '1',
//       name: 'Technology',
//     },
//     {
//       id: '2',
//       name: 'Health',
//     },
//     {
//       id: '3',
//       name: 'Finance',
//     },
//     {
//       id: '4',
//       name: 'Education',
//     },
//   ];

//   const DATA_POSTS: PostProps[] = [
//     {
//       id: '1',
//       userId: '101',
//       title: 'The Future of AI in Technology',
//       body: 'Artificial Intelligence (AI) is transforming the tech industry...',
//       categories: [
//         { id: '1', name: 'Technology' },
//         { id: '2', name: 'Health' },
//       ],
//     },
//     {
//       id: '2',
//       userId: '102',
//       title: '10 Tips for a Healthy Lifestyle',
//       body: 'Living a healthy life is crucial to overall well-being...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '3',
//       userId: '103',
//       title: 'Understanding Financial Freedom',
//       body: 'Financial freedom allows you to live life on your own terms...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '4',
//       userId: '101',
//       title: 'Online Learning and Education Trends',
//       body: 'The rise of online learning platforms is changing how education is delivered...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '5',
//       userId: '104',
//       title: 'The Impact of Blockchain on Finance',
//       body: 'Blockchain technology is revolutionizing the financial industry...',
//       categories: [
//         { id: '3', name: 'Finance' },
//         { id: '1', name: 'Technology' },
//       ],
//     },
//     {
//       id: '6',
//       userId: '105',
//       title: 'How to Maintain Mental Health',
//       body: 'Mental health is as important as physical health...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '7',
//       userId: '106',
//       title: 'The Role of Innovation in Business Success',
//       body: 'Innovation is key to staying competitive in today’s market...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '8',
//       userId: '101',
//       title: 'Best Practices for Remote Work',
//       body: 'Remote work has become a permanent fixture in the workplace...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '9',
//       userId: '107',
//       title: 'Investing in Cryptocurrency: Risks and Rewards',
//       body: 'Cryptocurrency is a volatile investment but offers high rewards...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '10',
//       userId: '108',
//       title: 'Nutrition Tips for a Balanced Diet',
//       body: 'A balanced diet is essential for maintaining good health...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '11',
//       userId: '109',
//       title: 'AI in Healthcare: Transforming Patient Care',
//       body: 'AI is revolutionizing healthcare by improving diagnostics...',
//       categories: [
//         { id: '1', name: 'Technology' },
//         { id: '2', name: 'Health' },
//       ],
//     },
//     {
//       id: '12',
//       userId: '110',
//       title: 'The Importance of Lifelong Learning',
//       body: 'Lifelong learning is crucial in a rapidly changing world...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '13',
//       userId: '111',
//       title: 'The Future of E-Commerce',
//       body: 'E-commerce continues to grow as more consumers prefer online shopping...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '14',
//       userId: '112',
//       title: 'How to Build a Strong Financial Foundation',
//       body: 'Building a strong financial foundation starts with budgeting...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '15',
//       userId: '113',
//       title: 'Developing a Growth Mindset',
//       body: 'A growth mindset is essential for personal and professional development...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '16',
//       userId: '114',
//       title: 'Sustainable Living: A Guide to Eco-Friendly Choices',
//       body: 'Sustainable living is all about making choices that benefit the planet...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '17',
//       userId: '115',
//       title: 'The Power of Automation in Business',
//       body: 'Automation is driving efficiency and productivity in businesses...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '18',
//       userId: '116',
//       title: 'Creating a Successful Investment Strategy',
//       body: 'A successful investment strategy is key to financial growth...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '19',
//       userId: '117',
//       title: 'Balancing Work and Study: Tips for Success',
//       body: 'Balancing work and study requires effective time management...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '20',
//       userId: '118',
//       title: 'Emerging Technologies Shaping the Future',
//       body: 'Emerging technologies like AI and blockchain are shaping the future...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '21',
//       userId: '119',
//       title: 'The Benefits of Meditation',
//       body: 'Meditation has numerous benefits for mental health...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '22',
//       userId: '120',
//       title: 'AI and Machine Learning Trends in 2024',
//       body: 'AI and machine learning are rapidly advancing in 2024...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '23',
//       userId: '121',
//       title: 'Effective Time Management Strategies',
//       body: 'Managing time effectively is crucial for productivity...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '24',
//       userId: '122',
//       title: 'Cryptocurrency Regulations: What You Need to Know',
//       body: 'Governments are increasingly regulating cryptocurrencies...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '25',
//       userId: '123',
//       title: 'Healthy Eating on a Budget',
//       body: 'Eating healthy doesn’t have to be expensive...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '26',
//       userId: '124',
//       title: 'The Impact of 5G Technology',
//       body: '5G is revolutionizing mobile communication with faster speeds...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '27',
//       userId: '125',
//       title: 'The Future of Work: Remote and Hybrid Models',
//       body: 'Remote and hybrid work models are the future of the workplace...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '28',
//       userId: '126',
//       title: 'How to Save Money: Tips and Tricks',
//       body: 'Saving money is easier with the right strategies...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '29',
//       userId: '127',
//       title: 'Fitness Routines for Busy Professionals',
//       body: 'Staying fit while managing a busy schedule is possible...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '30',
//       userId: '128',
//       title: 'The Role of Data in Business Decision-Making',
//       body: 'Data is essential for making informed business decisions...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '31',
//       userId: '129',
//       title: 'Mindfulness Practices for Daily Life',
//       body: 'Incorporating mindfulness into your daily routine can reduce stress...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '32',
//       userId: '130',
//       title: 'The Evolution of E-Learning Platforms',
//       body: 'E-learning platforms have transformed the education industry...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '33',
//       userId: '131',
//       title: 'Investing in Real Estate: A Beginner’s Guide',
//       body: 'Real estate investment can be a lucrative way to grow wealth...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '34',
//       userId: '132',
//       title: 'The Environmental Impact of Electric Vehicles',
//       body: 'Electric vehicles are reducing carbon emissions globally...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '35',
//       userId: '133',
//       title: 'How to Build Strong Relationships',
//       body: 'Building strong personal and professional relationships is key...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '36',
//       userId: '134',
//       title: 'The Future of Online Banking',
//       body: 'Online banking is becoming the preferred method for managing finances...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '37',
//       userId: '135',
//       title: 'Best Practices for Digital Marketing',
//       body: 'Digital marketing is essential for reaching a wider audience...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '38',
//       userId: '136',
//       title: 'Achieving Work-Life Balance',
//       body: 'Finding the right balance between work and life is crucial...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '39',
//       userId: '137',
//       title: 'The Importance of Cybersecurity',
//       body: 'Cybersecurity is more important than ever in the digital age...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '40',
//       userId: '138',
//       title: 'How to Start Your Own Business',
//       body: 'Starting a business requires careful planning and execution...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '41',
//       userId: '139',
//       title: 'The Rise of Sustainable Fashion',
//       body: 'Sustainable fashion is gaining popularity as consumers become more conscious...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '42',
//       userId: '140',
//       title: 'How to Reduce Your Carbon Footprint',
//       body: 'Reducing your carbon footprint helps protect the environment...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '43',
//       userId: '141',
//       title: 'The Basics of Stock Market Investing',
//       body: 'Investing in the stock market can be a powerful way to grow your wealth...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '44',
//       userId: '142',
//       title: 'The Benefits of Continuing Education',
//       body: 'Continuing education is essential for staying competitive in the job market...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '45',
//       userId: '143',
//       title: 'The Role of AI in Automating Businesses',
//       body: 'AI is increasingly being used to automate various business processes...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '46',
//       userId: '144',
//       title: 'Tips for Managing Stress in the Workplace',
//       body: 'Managing stress effectively is important for maintaining productivity...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//     {
//       id: '47',
//       userId: '145',
//       title: 'The Importance of Financial Planning',
//       body: 'Financial planning is crucial for achieving long-term financial goals...',
//       categories: [{ id: '3', name: 'Finance' }],
//     },
//     {
//       id: '48',
//       userId: '146',
//       title: 'How to Learn a New Skill Quickly',
//       body: 'Learning a new skill can be accelerated with the right techniques...',
//       categories: [{ id: '4', name: 'Education' }],
//     },
//     {
//       id: '49',
//       userId: '147',
//       title: 'The Impact of Social Media on Society',
//       body: 'Social media has changed how we interact and communicate...',
//       categories: [{ id: '1', name: 'Technology' }],
//     },
//     {
//       id: '50',
//       userId: '148',
//       title: 'How to Stay Physically Active at Work',
//       body: 'Staying active at work can improve both physical and mental health...',
//       categories: [{ id: '2', name: 'Health' }],
//     },
//   ];

  // export { DATA_PRODUCTS, DATA_CATEGORIES, DATA_POSTS };