import { Schema, string } from "yup";
import { InputListProps } from "@/types/form.type";

export const InputList: InputListProps[] = [
  {
    className: "mt-5 font-semibold text-xl",
    label: "Payment Information",
    name: "label",
    type: "label",
    validator: string(),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "Card Number",
    name: "cardNumber",
    type: "input",
    placeholder: "Your Card Number",
    isRequired: true,
    validator: string().required("Card Number is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "Card Holder",
    name: "cardHolder",
    type: "input",
    placeholder: "Your Card Holder",
    isRequired: true,
    validator: string().required("Card Holder is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "Expiration Date",
    name: "expirationDate",
    type: "input",
    placeholder: "Your Expiration Date",
    isRequired: true,
    validator: string().required("Expiration Date is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "CVV",
    name: "cvv",
    type: "input",
    placeholder: "Your CVV",
    isRequired: true,
    validator: string().required("CVV is required"),
  },
];


export const InputListAddress: InputListProps[] = [
  {
    label: "Full Name",
    name: "name",
    type: "input",
    placeholder: "Your Name",
    isRequired: true,
    validator: string().required("Name is required"),
  },
  {
    label: "Email",
    name: "email",
    type: "input",
    placeholder: "Your Email",
    isRequired: true,
    validator: string().required("Email is required"),
  },
  {
    label: "Phone",
    name: "phone",
    type: "input",
    placeholder: "Your Phone",
    isRequired: true,
    validator: string().required("Phone is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "Country",
    name: "country",
    type: "input",
    placeholder: "Your Country",
    isRequired: true,
    validator: string().required("Country is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "State",
    name: "state",
    type: "input",
    placeholder: "Your State",
    isRequired: true,
    validator: string().required("State is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "City",
    name: "city",
    type: "input",
    placeholder: "Your City",
    isRequired: true,
    validator: string().required("City is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "Postcode / ZIP",
    name: "zip",
    type: "input",
    placeholder: "Your Postcode / ZIP",
    isRequired: true,
    validator: string().required("Postcode / ZIP is required"),
  },
  {
    label: "Street Address",
    name: "address",
    type: "input",
    placeholder: "Your Street Address",
    isRequired: true,
    validator: string().required("Street Address is required"),
  },
];
