import { string } from "yup";
import { InputListProps } from "@/types/form.type";

export const InputListAddress: InputListProps[] = [
  {
    label: "Full Name",
    name: "name",
    type: "input",
    placeholder: "Your Name",
    isRequired: true,
    validator: string().required("Name is required"),
  },
  {
    label: "Email",
    name: "email",
    type: "input",
    placeholder: "Your Email",
    isRequired: true,
    validator: string().required("Email is required"),
  },
  {
    label: "Phone",
    name: "phone",
    type: "input",
    placeholder: "Your Phone",
    isRequired: true,
    validator: string().required("Phone is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "Country",
    name: "country",
    type: "input",
    placeholder: "Your Country",
    isRequired: true,
    validator: string().required("Country is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "State",
    name: "state",
    type: "input",
    placeholder: "Your State",
    isRequired: true,
    validator: string().required("State is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "City",
    name: "city",
    type: "input",
    placeholder: "Your City",
    isRequired: true,
    validator: string().required("City is required"),
  },
  {
    className: "basis-full lg:basis-1/2",
    label: "Postcode / ZIP",
    name: "zip",
    type: "input",
    placeholder: "Your Postcode / ZIP",
    isRequired: true,
    validator: string().required("Postcode / ZIP is required"),
  },
  {
    label: "Street Address",
    name: "address",
    type: "input",
    placeholder: "Your Street Address",
    isRequired: true,
    validator: string().required("Street Address is required"),
  },
];
